
/**
 * Defines the possible authors of a message in a chat session.
 */
export enum MessageRole {
  /** A message sent by the human user. */
  USER = 'user',
  /** A message generated by the AI model. */
  MODEL = 'model',
  /** A message representing an error from the API or application. */
  ERROR = 'error',
}

/**
 * Represents a single message within a chat session.
 */
export interface Message {
  /** The author of the message. */
  role: MessageRole;
  /** The text content of the message. */
  content: string;
}

/**
 * Represents a complete chat session, including its metadata and all messages.
 */
export interface ChatSession {
  /** A unique identifier for the chat session. */
  id: string;
  /** The title of the chat session, usually generated by the AI. */
  title: string;
  /** An array of all messages exchanged during the session. */
  messages: Message[];
}
